### ISSUE TITLE
hotkey in menu

### ISSUE THREAD

**Issue by kenedy3** [VortexShrimp/imgui-csgo-sdk#1]
how i make this?

**Comment by VortexShrimp** [comment]
Could you please elaborate? I'm not quite sure what you mean.

If you are referring to the menu key, that is currently in the `endscene` hook found in hooks.cpp and can be changed like so:
```cpp
// Change VK_INSERT to a key of your choice
if (GetAsyncKeyState(VK_INSERT) & 1)
	menu::opened = !menu::opened;
```

**Comment by z4chery** [comment]
He means like ImGui::Hotkey("aimbot key", &variables::aim_key);

**Comment by VortexShrimp** [comment]
Oh right, I thought so. 

OP, to do that you would need to create your own custom function using Dear ImGui. [Osiris](https://github.com/danielkrupinski/Osiris) has an implementation that can be found [here](https://github.com/danielkrupinski/Osiris/blob/2a8d3d1c18e9b108ae6a9e0476e033b04d7195e9/Osiris/GUI.cpp#L81) in GUI.cpp. It shouldn't be too difficult to add, all the code is there, good luck.

**Comment by z4chery** [comment]
Adding Osiris's hotkey feature makes it kinda wack, It displays a different key than the one u pressed, but the keybind you pressed(not the one that pops up on the hotkey thing) works. [https://streamable.com/yob0br](url). I think this happens because of `interfaces->inputSystem->virtualKeyToString(key))` is different in designers

**Comment by VortexShrimp** [comment]
Right, I believe that's happening because designer1337's base does not have a `virtualKeyToString()` function, but rather only the `button_code_to_string()`. So, I would assume that you are passing a virtual keycode into a function that takes the button code. I say this because Osiris's `virtualKeyToString()` function then calls the `virtualKeyToButtonCode()` function which converts the virtual code to the button code, this explains the discrepancy. To fix this, add the `virtualKeyToButtonCode()` function from [here](https://github.com/danielkrupinski/Osiris/blob/master/Osiris/SDK/InputSystem.h).

**Comment by z4chery** [comment]
Thanks, It worked.
